### ISSUE TITLE
Glitches with DataInspector

### ISSUE THREAD

**Issue by jwahlstrand** [JuliaGtk/Gtk4Makie.jl#10]
When using DataInspector, I'm seeing some weird glitches between the colon and the number:

![Screenshot from 2023-08-07 20-06-47](https://github.com/JuliaGtk/Gtk4Makie.jl/assets/4266000/ceca1baa-791e-4386-9f64-67d8ec16083f)

It looks fine in GLMakie so this is some sort of Makie+GTK issue.

**Comment by bilderbuchi** [comment]
I've also been seeing the same thing for a while, but haven't gotten around to reporting this, yet.
Good thing is that https://github.com/JuliaGtk/Gtk4Makie.jl/blob/main/examples/interactive.jl serves as a reproducer if you remove the code disabling the inspector.

**Comment by jwahlstrand** [comment]
Here's another clue: the same thing happens if you use certain symbols in axis labels or other text. Symbols that don't render right for me: @, ^, (, _, =, +, ', :, ;, /, }, |

Also, for me it's a Linux-only problem.

**Comment by bilderbuchi** [comment]
> Also, for me it's a Linux-only problem.

For completeness: I see this on Windows.

**Comment by jwahlstrand** [comment]
I was able to fix this by deleting the ".julia/makie" directory, which forces Makie to regenerate its "texture atlas". If this doesn't work for you, let me know and I'll reopen it.

**Comment by bilderbuchi** [comment]
Confirmed, updating package versions and deleting that folder remove the glitches, thanks!
