### ISSUE TITLE
Issue with Resolution

### ISSUE THREAD

**Issue by tknopp** [JuliaGtk/Gtk4Makie.jl#18]
Hi @jwahlstrand,

I am on Mac and try to use the Gtk4 Makie integration. Tested the widgets.jl code and got the following window.

<img width="594" alt="Bildschirmfoto 2024-07-13 um 12 35 26" src="https://github.com/user-attachments/assets/bc791ed8-bba2-40e8-8457-b2bb0e71419a">

It seems that there is something wrong with the resolution within the figure. When using regular GLMakie, everything looks sharp. Any idea?

**Comment by jwahlstrand** [comment]
The Makie 0.20 release included a lot of changes in GLMakie to better support retina displays. When I ported Gtk4Makie I tried but failed to get it to work as well as it does in GLMakie. I'll take another look. Unfortunately my old Mac laptop died, but I do have a desktop available.

Generally the Makie widget in this package is much more dangerous (in terms of crashing Julia) than the Makie window. It probably deserves a more prominent warning. I have spent a lot of time trying to fix #14...

**Comment by jwahlstrand** [comment]
Fixed on my Mac in the main branch. Let me know if it's not for you.

**Comment by tknopp** [comment]
Thanks, can confirm. Works now. One remaining issue in that concrete example is that it requires a resize to make the upper image look correct. Otherwise the aspect ratio does not fit (see original post above).

**Comment by jwahlstrand** [comment]
I don't see that on my Mac. But the "widgets" example has other problems on Mac OS that don't appear on Linux for me. I opened a new issue, #19.
