### ISSUE TITLE
Screen only works one time

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGtk/Gtk4Makie.jl#2]
Great work, with figuring out the problem :) 
It works now, but only one time it seems... If I close the window and create a new one, it will stay blank.
Is this a Windows issue, or do you face the same problem?
Btw, @jwahlstrand, would be nice to have a quick chat, maybe on the julia slack or makie discord?
Julia: http://julialang.slack.com
Makie: https://discord.gg/dwxUVEH6Tz

**Comment by jwahlstrand** [comment]
Yeah there is a lot more work to do! I have to go to my day job right now but I will join slack in the next few days.

**Comment by jwahlstrand** [comment]
BTW I think that problem is related to the hard-coded ID of 2. It's not just Windows.

**Comment by jwahlstrand** [comment]
I think this is fixed now.
