### ISSUE TITLE
Dialog makes Julia freeze

### ISSUE THREAD

**Issue by bilderbuchi** [JuliaGtk/Gtk4Makie.jl#4]
I tried to extend your example from runtests.jl with a file chooser  dialog: 
```julia
using GtkMakie, GLMakie, Gtk4

screen = GtkMakie.GTKScreen(resolution=(800, 800))

display(screen, scatter(1:4))

g=grid(screen)

insert!(g,1,:top)
g[1,1]=GtkLabel("a title widget")

load_button = GtkButton("load file")
g[1,3]= load_button

function on_load(s)
    file = open_dialog("Load some file") # makes Julia freeze
    # file = open_dialog("Load HDdfF5 file", s) # yields a StackOverflowError
    @info file
    # more other stuff will happen here later
end
signal_connect(on_load, load_button, "clicked")
```
As-is, when pressing Cancel or Open with a file selected, Julia freezes and stops responding, has to be killed.
Alternatively, passing a parent like in the commented line leads to a StackoverflowError.

Is that because of something I am doing wrong?

This is on Windows 10, VS Code, Julia 1.8.5., using the current dev'd tips of GtkMakie and Gtk4.

Note: I am not using the `do` syntax because I'm not familiar enough with it and because my "real" callback has an optional keyword argument so I can also trigger it from elsewhere in the code (`function on_load(s; file=nothing)`)

**Comment by jwahlstrand** [comment]
Dialogs were changed a lot in GTK4 and they need way better documentation. This, which is equivalent to the `do` syntax, works for me:
```
...
g[1,3]= load_button

function cb(file)
    @info file
    # do other stuff here - maybe your "real" callback?
end

function on_load(s)
    open_dialog(cb, "Load some file")
end
signal_connect(on_load, load_button, "clicked")
```

**Comment by bilderbuchi** [comment]
Ha, I did not realise that (probably due to unfamiliarity with Julia, Gtk _and_ Makie 😅 ). 
This works, sorry for the noise!
