### ISSUE TITLE
Saving figures

### ISSUE THREAD

**Issue by bilderbuchi** [JuliaGtk/Gtk4Makie.jl#5]
If I extend the test you recently added with "save figure" functionality, I only get a white canvas in the resulting file.
```julia
using Gtk4
using GtkMakie, GLMakie

screen = GtkMakie.GTKScreen(resolution=(800, 800),title="10 random numbers")
display(screen, lines(rand(10)))
ax=current_axis()
f=current_figure()

g=grid(screen)

g[1,2]=GtkButton("Generate new random plot")

function gen_cb(b)
    empty!(ax)
    lines!(ax,rand(10))
    Gtk4.queue_render(GtkMakie.win2glarea[screen.glscreen])
end

signal_connect(gen_cb,g[1,2],"clicked")

g[1,3]=GtkButton("Save!")

function save_cb(b)
    println("Saving in $(pwd())")
    # hitting the button closes the app!
    GLMakie.save("test.png", f) # saves an empty canvas
    # GLMakie.save("test.png", screen.root_scene) # saves an empty canvas, too
end

signal_connect(save_cb,g[1,3],"clicked")
```
In addition, but that might be some limitation of Makie, the application closes when you hit "Save".

**Comment by jwahlstrand** [comment]
Yup, I'm seeing the same thing. It does look like in GLMakie the window also closes when you save, which must be intentional. I have an idea about what's happening with the blank canvas but won't have time to work on it for a while.

**Comment by bilderbuchi** [comment]
Sure! 
I'd offer to investigate myself, but I'd need waay more Julia expertise to be useful, right now many error messages are quite inscrutable, and function docstrings don't seem to be en vogue in the ecosystem (which makes poking around in source code less productive).

I managed to work around the closing application problem for the moment by doing, essentially, `GLMakie.save(filename, Makie.colorbuffer(screen))` - I have no idea if that is a "clean" workaround 😝 , but at least that thing doesn't close anymore when hitting the save button.
I assume this won't be sufficient when later saving to pdf (via `backend=CairoMakie`), but one step at a time. :-P

**Comment by SimonDanisch** [comment]
Same as https://github.com/MakieOrg/Makie.jl/issues/2675 I suppose...

**Comment by bilderbuchi** [comment]
Why do you suppose that? 
https://github.com/MakieOrg/Makie.jl/issues/2675 uses a different backend for saving, saves the file correctly, and leaves an empty figure behind.
This issue is that saving doesn't work correctly in the first place, and secondarily that the Gtk application is closed by the act of saving. CairoMakie is not involved at all here.

Are you suggesting that all three issues have the same root cause/fix?

**Comment by SimonDanisch** [comment]
I'm not 100% sure, but the symptom is very similar, and I think the Gtk screen is treated in the linked function like a screen from a different backend (`GLMakie.Screen{GLFW.Window} !== GLMakie.Screen{Gtk4.Window}`)!

**Comment by SimonDanisch** [comment]
Actually, I just wanted to recommend `GLMakie.save(filename, Makie.colorbuffer(screen))` as a workaround before I saw that you actually already found that work around.
So I think it's a fair solution for now (this way, we're not calling into `save(..., fig)`, which will try to create a `GLMakie.Screen{GFLW.Window}`, since that part of the infrastructure is not aware of the Gtk "backend", yet.

**Comment by bilderbuchi** [comment]
Thanks. Yeah I stumbled over that in another issue/discussion. I figured it's a way to "copy" the figure contents. That way, the current behaviour destroys the copy and doesn't bother the original (that I want to continue using in the GUI). 

This does not solve the saving-creates-a-blank-file issue, though -- I'm not sure if you're suggesting in your last comment that it should?

**Comment by SimonDanisch** [comment]
I'm not sure what you mean...
You said:

>I managed to work around the closing application problem for the moment by doing, essentially, GLMakie.save(filename, Makie.colorbuffer(screen))

So this works right? I haven't tried it myself but it sounds like it should work.
I haven't proposed any solution, just agreed that the work around you found should be pretty valid...

**Comment by bilderbuchi** [comment]
> So this works right? I haven't tried it myself but it sounds like it should work.

Yes, this makes my application not close on save anymore. However, the files that are saved are still empty/white. 
There are basically two problems present in this issue (saving-creates-a-blank-file and saving-closes-the-app) -- should I file two separate issues to avoid confusion?

**Comment by jwahlstrand** [comment]
The blank file part of this might have something to do with the `framebuffer_id[]` business that had to be added to make GtkGLArea work. I'll investigate when I get a chance.

**Comment by jwahlstrand** [comment]
I just implemented something in the interactive example that produces non-blank files for me. I'd consider it a temporary solution... I don't understand why `Makie.save(filename, f)` doesn't work, and it would be good to get it working.

**Comment by bilderbuchi** [comment]
Nice! I can confirm that this is working, I can now export plots, thanks!
