### ISSUE TITLE
Registered package?

### ISSUE THREAD

**Issue by mashu** [JuliaGtk/Gtk4Makie.jl#6]
Any plans for making it registered package?
This looks very useful for displaying realtime data in an app.

**Comment by jwahlstrand** [comment]
Yes, I think it's useful enough now. I'll register it pretty soon.

**Comment by mashu** [comment]
Also what's the difference between GTK.jl and GTK4.jl ? Isn't GTK one the
official one ?

**Comment by SimonDanisch** [comment]
There is no official one. `Gtk.jl` is the older one, and `Gtk4.jl` is the new one, soon to replace `Gtk.jl`, since `Gtk.jl` has lots of problems and can't be upgraded easily to use `Gtk4`.

**Comment by jwahlstrand** [comment]
It's now registered (renamed Gtk4Makie to satisfy the registry's naming guidelines)

**Comment by SimonDanisch** [comment]
Hah, thats a pretty good name :)
